### ISSUE TITLE
图片数据处理方法的讨论

### ISSUE THREAD

**Issue by hduyyg** [apachecn/kaggle#67]
可以尝试图片处理中缩放，来将原始图片缩小，较少特征。
之后进行锐化，使图片更加清晰，特征更突出。

**Comment by yudonglin506311858** [comment]
数据增强data augmentation是不是也可以用上？https://zhuanlan.zhihu.com/p/29513760。我们必须知道做出的统计推断是有一定概率是错误的。第一类统计错误是弃真，即原假设成立（不存在差异）但我们放弃原假设，接受备择假设，即真实情况不存在差异但我们错误认为有差异；第二类统计错误是取伪，即原假设不成立但我们选择接受原假设，即真实情况存在差异但我们错误认为没有差异。统计错误是必然会存在的，一个高了另一个可能就会降低，因此只要增大样品量才能同时降低这两种统计学错误，即提高特异性和敏感性。但具体怎么做还是手残。

**Comment by hduyyg** [comment]
可以的，这个链接里面就有我之前处理数据时，用到的图片缩放

**Comment by rujinshi** [comment]
[NMF非负矩阵分解？](http://blog.csdn.net/pipisorry/article/details/52098864)
 **NMF最成功的一类应用是在图像的分析和处理领域？** 
[NMF维基百科](https://en.wikipedia.org/wiki/Non-negative_matrix_factorization#Applications)

对于降维今天看了一下，我之前听到最多的就是PCA。但似乎不是那么回事。
[什么时候使用PCA和LDA？](https://www.zhihu.com/question/35666712)
PCA是无类别信息，不知道样本属于哪个类，用PCA，通常对全体数据操作。LDA有类别信息，投影到类内间距最小and类间间距最大也有一些算法，先用PCA搞一遍，再用LDA搞一遍，也有相反。反正有论文是这么搞的，至于是不是普适，要看具体问题。
在有监督降维中还有一个最大边缘准则法(Maximum Margin Criterion,MMC)。
我更想用NMF+RF试一下
PCA也试一下。
