### ISSUE TITLE
Adaboost原算法提高分类性能

### ISSUE THREAD

**Issue by hduyyg** [apachecn/kaggle#81]
我现在还没怎么看懂，有人能浅显的讲一下吗？

**Comment by rujinshi** [comment]
是集成学习（ensemble learning）中的一种。通过训练得到一系列弱分类器（基本分类器），将这些弱分类器组合成一个强分类器，以达到比单一分类器更好的泛化性能。
1.个体分类器存在强依赖关系，必须串行生成—Boosting。Boosting中的代表的算法就是AdaBoost，一般用于二分类。其理解方式为基于**基学习器的线性组合**来最小化指数损失函数。具体说来，首先提高那些被前一轮弱分类器错误分类样本的权值，而降低那些被正确分类样本的权值。接着，加大分类误差率小的弱分类器的权值，使其在表决中起较大的作用，减小分类误差率大的弱分类器的权值，使其在表决中其较小的作用。Boosting主要关注**偏差。**
2.个体分类器不存在强依赖关系，可以并行生成——[Bagging](https://en.wikipedia.org/wiki/Bootstrap_aggregating)和RF(Bagging的进化版)。Bagging主要关注**方差**，所以在不剪枝决策树、神经网络等易受样本扰动的学习器上效果更明显。
@hduyyg

**Comment by hduyyg** [comment]
get

**Comment by hduyyg** [comment]
http://blog.csdn.net/guyuealian/article/details/70995333
这个链接有数据显示，理解可能会好一点
