### ISSUE TITLE
adaboost：不同分类算法的有效利用

### ISSUE THREAD

**Issue by hduyyg** [apachecn/kaggle#82]
http://blog.csdn.net/guyuealian/article/details/70995333
感觉可以用在我们基本算法结束之后，对于不同算法的整合上，比简单的选择某个样本在这些算法中出现最多的最为最终结果要好。

**Comment by LGTH** [comment]
整合不同算法的思路和投票算法是一个意思，sklearn里面用VotingClassifier来实现，而AdaBoost是针对同一个训练集训练不同的分类器，把弱分类器分类器集合构成强分类

**Comment by hduyyg** [comment]
受教
